#+title: Delta Emacs configuration
#+author: Caesar X Insanium
#+startup: fold
* Purpose
This is my literate config file for Emacs. It uses =straight.el=. And does not use evil or general anymore.
* Straight.el
#+begin_src elisp
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name
	"straight/repos/straight.el/bootstrap.el"
	(or (bound-and-true-p straight-base-dir)
	    user-emacs-directory)))
      (bootstrap-version 7))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
	(url-retrieve-synchronously
	 "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
	 'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))

(straight-use-package 'el-patch)
(straight-use-package 'use-package)
(setq straight-use-package-by-default 't)
#+end_src
* Init
Here will the contents of the init file. Not tangled since this line is explicitly inside of =init.el=
#+begin_src emacs-lisp :tangle no
(org-babel-load-file (concat (expand-file-name user-emacs-directory) "README.org"))
#+end_src
Make sure that a =custom.el= file exists.

* Which Key
Which key so that I know what exactly I am doing.
#+begin_src elisp  
(use-package which-key
  :straight t
  :config
  (which-key-mode 1))
#+end_src
* Emacs
Emacs Specific Configuration and the like.
#+begin_src elisp 
(use-package emacs
  :straight (:type built-in)
  ;; these bindings override default options.
  :bind (("C-s" . consult-line)
	 ("C-x f" . consult-recent-file)
	 ("C-x M-f" . consult-fd)
	 ("C-x M-t" . consult-theme)
	 ("C-x C-c" . save-buffers-kill-terminal)
	 ("C-x c c" . compile)
	 ("C-x c k" . kill-compilation))
  :hook ((compilation-filter . ansi-color-compilation-filter)
         (prog-mode . (lambda ()
                        (interactive)
                        (setq display-line-numbers 'relative)
                        (display-line-numbers-mode 1)
                        (setq truncate-lines t)
			(electric-indent-mode 1))))
  :config
  (setq custom-file (concat user-emacs-directory "custom.el"))
  (load custom-file))
#+end_src

#+RESULTS:
: kill-compilation

** Modes
#+begin_src elisp
; keep parenthesis balanced. must be disabled in lispy files. Show matching
(electric-pair-mode 1)
(show-paren-mode 1)
(save-place-mode 1)
;; minibuffer history is saved
(savehist-mode t)
;; required for consult-recent-file
(recentf-mode t)
;; highlight line containing point
(global-hl-line-mode 1)
;; revert files changed from disk
(global-auto-revert-mode t)
;; show column number
(column-number-mode 1)

;; disable graphical bullshit
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
;; Disable this for most file types. Prog mode hook will have it
(electric-indent-mode -1)
#+end_src

** Variables

#+begin_src elisp 
;; Set Variables elisp
(setq indent-tabs-mode nil
      tab-width 2
      c-basic-offset 2) ;; tab key will no longer insert tab characters
(setq display-line-numbers 'relative)
(setq backup-directory-alist '((".*" . "~/.local/share/Trash/Files")))
(setq make-backup-files nil)
(setq inhibit-startup-screen t)

(setq native-comp-jit-compilation t)
(setq truncate-lines nil)
#+end_src

** Custom Commands

#+begin_src elisp
(defun my-reload-emacs ()
  (interactive)
  (load-file "~/.emacs.d/init.el"))

(defun my-reload-buffer ()
  (interactive)
  (revert-buffer :ignore-auto :noconfirm))
(defun my-show-window-dims ()
  (interactive)
  (message "Width: %s, Height :%s" (window-total-width) (window-total-height)))
(defun my-choose-info-manual ()
  (interactive)
  (completing-read "Choose Manual:" my-info-manual-list))
(defun my-is-deamon ()
  (interactive)
  (if (daemonp)
      (message "Running in Daemon")
    (message "Running Solo")))
#+end_src

* Org
Org mode specific Configuration. I still have to read the Org Mode Manual

What if I reserved single letter bindings for global minor modes and modified bindings for current major mode?
#+begin_src elisp
(use-package org
  :straight (:type built-in)
  :bind (:map org-mode-map
              ;; a lot of these bindings are defaults on org-mode emacs
              ("C-c C-c" . org-babel-execute-src-block)
              ("C-c C-j" . org-goto) ;; I like to be explicit, this binding is default
              ("C-c C-t" . org-babel-tangle)
              ("C-c C-e" . org-export-dispatch)
              ("C-c C-," . org-insert-structure-template)
	      ("C-c C-[" . org-do-promote)
	      ("C-c C-]" . org-do-demote )
	      ("C-c 0" . consult-outline))
  :hook (org-mode . (lambda ()
   ;                   (interactive)
                      (visual-line-mode 1)
		      (org-indent-mode 1)))
  :config
  (setq org-src-fontify-natively t) ;; enable syntax highlighting in source blocks in org mode
  (setq org-src-preserve-indentation nil) ;; preserve leading whitespace on export
  (setq org-edit-src-content-indentation 0) ;; disable that annoying bug where more indentation is added on newline)
  ;; confirmation of arbitrary code execute is for losers
  (setq org-confirm-babel-evaluate nil)
  (setq org-startup-folded 'fold))
#+end_src

#+RESULTS:
: consult-outline

* Enhancements
Random plugins that help with everything. Make things not so unbearable.
** Vertico
Replace or fix
Check the github page for more information and to read documentation.
[[https://github.com/minad/vertico][Vertico Docs]]

#+begin_src elisp :tangle yes
(use-package vertico
  :straight t
  :config
  ;; Allows for completion candidates to viewed in the minibuffer and selected from
  ;; there
  (vertico-mode 1))
#+end_src

#+RESULTS:
: t

** Orderless

Allows for more flexible completion candidate matching.

#+begin_src elisp
(use-package orderless
  :config
  (setq completion-styles '(orderless basic)
        completion-catagory-overrides '((file (styles basic partial-completion)))))
#+end_src

** Consult

Searching and completion.

#+begin_src elisp
;; Example configuration for Consult
(use-package consult
  ;; Replace bindings. Lazily loaded by `use-package'.
  :bind (;; C-c bindings in `mode-specific-map'
         ([remap Info-search] . consult-info)
	 ;; C-x bindings in `ctl-x-map'
	 ("C-x M-:" . consult-complex-command)	   ;; orig. repeat-complex-command
	 ("C-x b" . consult-buffer)		   ;; orig. switch-to-buffer
	 ("C-x 4 b" . consult-buffer-other-window) ;; orig. switch-to-buffer-other-window
	 ("C-x 5 b" . consult-buffer-other-frame)  ;; orig. switch-to-buffer-other-frame
	 ("C-x t b" . consult-buffer-other-tab)	   ;; orig. switch-to-buffer-other-tab
	 ("C-x r b" . consult-bookmark)		   ;; orig. bookmark-jump
	 ("C-x p b" . consult-project-buffer)	   ;; orig. project-switch-to-buffer
	 ;; Custom M-# bindings for fast register access
	 ("M-#" . consult-register-load)
	 ("M-'" . consult-register-store)	   ;; orig. abbrev-prefix-mark (unrelated)
	 ("C-M-#" . consult-register)
	 ;; Other custom bindings
	 ("M-y" . consult-yank-pop)		   ;; orig. yank-pop
	 ;; M-g bindings in `goto-map'
	 ("M-g e" . consult-compile-error)
	 ("M-g f" . consult-flymake)		   ;; Alternative: consult-flycheck
	 ("M-g g" . consult-goto-line)		   ;; orig. goto-line
	 ("M-g M-g" . consult-goto-line)	   ;; orig. goto-line
	 ("M-g o" . consult-outline)		   ;; Alternative: consult-org-heading
	 ("M-g m" . consult-mark)
	 ("M-g k" . consult-global-mark)
	 ("M-g i" . consult-imenu)
	 ("M-g I" . consult-imenu-multi)
	 ;; M-s bindings in `search-map'
	 ("M-s d" . consult-find)		   ;; Alternative: consult-fd
	 ("M-s c" . consult-locate)
	 ("M-s g" . consult-grep)
	 ("M-s G" . consult-git-grep)
	 ("M-s r" . consult-ripgrep)
	 ("M-s l" . consult-line)
	 ("M-s L" . consult-line-multi)
	 ("M-s k" . consult-keep-lines)
	 ("M-s u" . consult-focus-lines)
	 ;; Isearch integration
	 ("M-s e" . consult-isearch-history)
	 :map isearch-mode-map
	 ("M-e" . consult-isearch-history)	   ;; orig. isearch-edit-string
	 ("M-s e" . consult-isearch-history)	   ;; orig. isearch-edit-string
	 ("M-s l" . consult-line)		   ;; needed by consult-line to detect isearch
	 ("M-s L" . consult-line-multi)		   ;; needed by consult-line to detect isearch
	 ;; Minibuffer history
	 :map minibuffer-local-map
	 ("M-s" . consult-history)		   ;; orig. next-matching-history-element
	 ("M-r" . consult-history))		   ;; orig. previous-matching-history-element

  ;; Enable automatic preview at point in the *Completions* buffer. This is
  ;; relevant when you use the default completion UI.
  :hook (completion-list-mode . consult-preview-at-point-mode)

  ;; The :init configuration is always executed (Not lazy)
  :init

  ;; Tweak the register preview for `consult-register-load',
  ;; `consult-register-store' and the built-in commands.  This improves the
  ;; register formatting, adds thin separator lines, register sorting and hides
  ;; the window mode line.
  (advice-add #'register-preview :override #'consult-register-window)
  (setq register-preview-delay 0.5)

  ;; Use Consult to select xref locations with preview
  (setq xref-show-xrefs-function #'consult-xref
	xref-show-definitions-function #'consult-xref)

  ;; Configure other variables and modes in the :config section,
  ;; after lazily loading the package.
  :config

  ;; Optionally configure preview. The default value
  ;; is 'any, such that any key triggers the preview.
  ;; (setq consult-preview-key 'any)
  ;; (setq consult-preview-key "M-.")
  ;; (setq consult-preview-key '("S-<down>" "S-<up>"))
  ;; For some commands and buffer sources it is useful to configure the
  ;; :preview-key on a per-command basis using the `consult-customize' macro.
  (consult-customize
   consult-theme :preview-key '(:debounce 0.2 any)
   consult-ripgrep consult-git-grep consult-grep consult-man
   consult-bookmark consult-recent-file consult-xref
   consult--source-bookmark consult--source-file-register
   consult--source-recent-file consult--source-project-recent-file
   ;; :preview-key "M-."
   :preview-key '(:debounce 0.4 any))

  ;; Optionally configure the narrowing key.
  ;; Both < and C-+ work reasonably well.
  (setq consult-narrow-key "<") ;; "C-+"

  ;; Optionally make narrowing help available in the minibuffer.
  ;; You may want to use `embark-prefix-help-command' or which-key instead.
  ;; (keymap-set consult-narrow-map (concat consult-narrow-key " ?") #'consult-narrow-help)
)
#+end_src

** Icons

#+begin_src elisp
(use-package all-the-icons)
#+end_src

** Themes

*** Everforrest
#+begin_src elisp
(straight-use-package
 '(everforest :repo "https://github.com/Theory-of-Everything/everforest-emacs.git"))
#+end_src

*** Doom Themes

#+begin_src elisp
(use-package doom-themes
  :config
  ;; Global settings (defaults)
  (setq doom-themes-enable-bold t    ; if nil, bold is universally disabled
	doom-themes-enable-italic t) ; if nil, italics is universally disabled

  ;; Enable flashing mode-line on errors
  (doom-themes-visual-bell-config)
  ;; Enable custom neotree theme (all-the-icons must be installed!)
  (doom-themes-neotree-config)
  ;; or for treemacs users
  (setq doom-themes-treemacs-theme "doom-atom") ; use "doom-colors" for less minimal icon theme
  (doom-themes-treemacs-config)
  ;; Corrects (and improves) org-mode's native fontification.
  (doom-themes-org-config))
#+end_src

*** Catppuccin

#+begin_src elisp
(straight-use-package 'catppuccin-theme
		      :config
		      (setq catppuccin-flavor 'mocha))
#+end_src

#+RESULTS:

*** Solarized
#+begin_src elisp :tangle no
(use-package emacs-color-theme-solarized
  :vc (:url "https://github.com/sellout/emacs-color-theme-solarized.git"
	    :branch "master")
  :config
  (add-to-list 'custom-theme-load-path
	       "~/.emacs.d/elpa/emacs-color-theme-solarized"))
#+end_src

*** Gruvbox
#+begin_src elisp
(use-package gruvbox-theme)
#+end_src

#+RESULTS:

*** Modus Themes
#+begin_src elisp
(use-package modus-themes
  :ensure t
  :demand t
  :init
  ;; Starting with version 5.0.0 of the `modus-themes', other packages
  ;; can be built on top to provide their own "Modus" derivatives.
  ;; For example, this is what I do with my `ef-themes' and
  ;; `standard-themes' (starting with versions 2.0.0 and 3.0.0,
  ;; respectively).
  ;;
  ;; The `modus-themes-include-derivatives-mode' makes all Modus
  ;; commands that act on a theme consider all such derivatives, if
  ;; their respective packages are available and have been loaded.
  ;;
  ;; Note that those packages can even completely take over from the
  ;; Modus themes such that, for example, `modus-themes-rotate' only
  ;; goes through the Ef themes (to this end, the Ef themes provide
  ;; the `ef-themes-take-over-modus-themes-mode' and the Standard
  ;; themes have the `standard-themes-take-over-modus-themes-mode'
  ;; equivalent).
  ;;
  ;; If you only care about the Modus themes, then (i) you do not need
  ;; to enable the `modus-themes-include-derivatives-mode' and (ii) do
  ;; not install and activate those other theme packages.
  (modus-themes-include-derivatives-mode 1)
  :bind
  (("<f5>" . modus-themes-rotate)
   ("C-<f5>" . modus-themes-select)
   ("M-<f5>" . modus-themes-load-random))
  :config
  ;; Your customizations here.  All customizations must evaluated
  ;; BEFORE loading the theme.
  (setq modus-themes-to-toggle '(modus-operandi modus-vivendi)
        modus-themes-to-rotate modus-themes-items
        modus-themes-mixed-fonts t
        modus-themes-variable-pitch-ui t
        modus-themes-italic-constructs t
        modus-themes-bold-constructs t
        modus-themes-completions '((t . (bold)))
        modus-themes-prompts '(bold)
        modus-themes-headings
        '((agenda-structure . (variable-pitch light 2.2))
          (agenda-date . (variable-pitch regular 1.3))
          (t . (regular 1.15))))

  (setq modus-themes-common-palette-overrides nil))
#+end_src
*** Lambda Theme
#+RESULTS:
: modus-themes-load-random
#+begin_src elisp
(use-package lambda-themes
  :straight (:type git :host github :repo "lambda-emacs/lambda-themes") 
  :custom
  (lambda-themes-set-italic-comments t)
  (lambda-themes-set-italic-keywords t)
  (lambda-themes-set-variable-pitch t) 
  :config
  ;; load preferred theme 
  )
#+end_src

#+RESULTS:
*** Nano Theme
#+begin_src elisp
(straight-use-package '(nano-theme :type git :host github
                                   :repo "rougier/nano-theme"))
#+end_src

#+RESULTS:
: t
*** Mindre
#+begin_src elisp
(use-package mindre-theme
    :ensure t
    :custom
    (mindre-use-more-bold nil)
    (mindre-use-faded-lisp-parens t)
    :config
    (load-theme 'mindre t))
#+end_src

#+RESULTS:
: t

** Modeline

Just use the doom mode bar fuck it

#+begin_src elisp
(use-package doom-modeline
   
  :config
  (setq doom-moneline-time-icon t)
  (doom-modeline-mode 1))
#+end_src

** Helpful

#+begin_src elisp
  (use-package helpful
    :bind (("C-h f" . helpful-callable) ;; function
	   ("C-h v" . helpful-variable) 
	   ("C-h k" . helpful-key)
	   ("C-h x" . helpful-command)
	   ("C-h C-d" . helpful-at-point)
	   ("C-h F" . helpful-function)))
#+end_src

#+RESULTS:
: helpful-function

** Window Managment
We will use a package named switch-window in order to allow easy switching of windows when hitting
"C-x o". Better fucking defaults too.
#+begin_src elisp
(use-package switch-window
  :bind (("C-x o" . switch-window)
	 ("C-x C-o" . other-window)
	 ("C-x 1" . switch-window-then-maximize)
	 ("C-x 2" . switch-window-then-split-below)
	 ("C-x 3" . switch-window-then-split-right)
	 ("C-x 0" . switch-window-then-delete)
	 ("C-x 4 d" . switch-window-then-dired)
	 ("C-x 4 f" . switch-window-then-find-file)))
#+end_src

#+RESULTS:
: switch-window-then-find-file

** Golden Ratio Splits
To get that BSPWM goodness

#+begin_src elisp
(straight-use-package
 '(golden-ratio :type git :host github :repo "roman/golden-ratio.el"))

(golden-ratio-mode 1)
#+end_src
** Rainbows
Rainbow parenthesis. Enable fucking everywhere.
#+begin_src elisp
(use-package rainbow-delimiters
  :hook (prog-mode . rainbow-delimiters-mode))

(use-package rainbow-mode)
#+end_src

* Projects
** Git Integration: Magit
Magit Magit Magit
#+begin_src elisp
(use-package magit)
#+end_src
** Project.el
Check out the manual page. [[info:emacs#Project File Commands][Project Functions and Default Keybindings]]. all of the default project keybindings start with 'C-x p'
- TODO (consult-key project prefix consult-project)
* Editing
** Formatting
#+begin_src elisp
(use-package format-all
  :preface
  (defun ian/format-code ()
    "Auto-format whole buffer."
    (interactive)
    (if (derived-mode-p 'prolog-mode)
	(prolog-indent-buffer)
      (format-all-buffer)))
  :config
  (add-hook 'prog-mode-hook #'format-all-ensure-formatter))
#+end_src

** Lisp Editing
Change to paredit. Learn Paredit. Download cheatsheet. Learn stuff
#+begin_src elisp :tangle yes
(use-package paredit
  :hook ((common-lisp-mode scheme-mode clojure-mode emacs-lisp-mode) . paredit-mode))
#+end_src

* Programming
** TLDR
TLDR pages inside of emacs for programming and command line goodness
#+begin_src elisp
(use-package tldr)
#+end_src
** XRef: Lookup definitions and references of Symbols
Used in conjunction with Etags. I need to read this particular section of the GNU Emacs Manual. [[info:emacs#Xref][Emacs XREF]]
Xref is used for searching the definition of language symbols, references
[[info:emacs#Looking Up Identifiers][XREF Docs Emacs Manual]].
A suitable tags file can be created with =etags= command. This is the only way I
know of that can generate Emacs compatible tags which is called =TAGS=
I have forgotten how to make org links.
Xref buffer has some built in bindings. [[info:emacs#Xref Commands][XREF Mode Bindings]] 

* Language Specific
It seems that emacs will mostly be a lisp editor.
** C/C++/Java CC Mode
Starting this config from scratch. I have no idea what to do now.
** Common Lisp
*** Slime
I have finally relented and decided to the the CommonLisp way.
#+begin_src elisp
(use-package slime
  :init
  (setq inferior-lisp-program "sbcl"))
#+end_src

#+RESULTS:
** Racket
Racket mode and Quak
#+begin_src elisp
(use-package racket-mode)
#+end_src
** Scheme: Geiser
Why are we still here just to suffer. Geiser is the way to go.
Scheme completion is done with [[info:guile#Readline Functions][guile#Readline Functions]]
#+begin_src elisp
(use-package geiser
  :config
  (setq geiser-default-implementation '(guile))
  (setq geiser-guile-binary "/usr/bin/guile"))
(use-package geiser-guile)
#+end_src
** Clojure
#+begin_src elisp
(use-package clojure-mode)
(use-package cider)
#+end_src
** Haskell
I will now do Haskell programming.
#+begin_src elisp
(use-package haskell-mode)
#+end_src

#+RESULTS:
** Golang
This is provided by a certain little project
#+begin_src elisp
(defun my-go-mode-settings ()
  "Set Go industry-standard indentation and tab settings."
  (setq-local indent-tabs-mode t)   ; Use tabs, not spaces, for indentation
  (setq-local tab-width 4)          ; Go standard: tab width = 8
  (setq-local standard-indent 4)    ; Ensure consistent indentation step
  ;; If you use go-mode's own variable, set it as well
  (setq-local go-tab-width 4))
(use-package go-mode
  :hook (go-mode . my-go-mode-settings))
#+end_src

#+RESULTS:
| my-go-mode-settings | my-go-settings | doom-modeline-env-setup-go |

Trying to test.
#+begin_src go
import "Fmt"
func main(){
	PrintLn("Hello World!\n")
}
#+end_src

* Markup And Documents
** Markdown
I have to be able to view and edit Markdown files with the same ease as Org.
[[https://jblevins.org/projects/markdown-mode/][Documentation]]
I will continue configuring this stuff later.
#+begin_src elisp
(use-package markdown-mode
  :hook (markdown-mode . (lambda ()
			   (interactive)
			   (setq truncate-lines t))))
#+end_src
